### PR TITLE
Create Home Page

### PR DESCRIPTION
**Pull request by nghiahn-0358**
[Ticket #68690](https://edu-redmine.sun-asterisk.vn/issues/68690)

### CODE REVIEW

**Comment by nghiahn-0358** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented
gái ơi, 4 commit nè,  nhìu quá, rebase đi, nếu ko tự tin, báo chị support

**Comment by KhangHg** [comment]
ready

**Comment by KhangHg** [comment]
ready

**Comment by vanvtt-0952** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented

**Comment by KhangHg** [comment]
ready

**Comment by nghiahn-0358** [comment]
ready

**Pull request merged**
